<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CompanySetting extends Model
{
    protected $fillable = [
        'name',
        'footer_description',
        'footer_email',
        'footer_phone',
        'footer_logo',
        'facebook',
        'instagram',
        'tiktok',
        'youtube',
        'legal_company_name',
        'about_eyebrow',
        'about_title',
        'about_lead',
        'about_intro',
        'about_who',
        'about_differentials',
        'about_process',
        'about_mission',
        'about_story',
        'about_cta_label',
        'about_cta_url',
        'about_supporting',
        'about_stats',
        'about_image_src',
        'about_image_alt',
        'about_image_caption',
        'about_trust_title',
        'about_trust_items',
        'about_values',
        'about_show_narrative',
        'about_show_stats',
        'about_show_image',
        'about_show_trust',
        'about_show_values',
        'about_show_cta',
        'services_title',
        'services_intro',
        'services_cta_label',
        'services_cta_url',
        'services_show_section',
        'services_show_cta',
        'location_title',
        'location_description',
        'location_map_embed',
        'location_address',
        'location_hours',
        'location_email',
        'location_phone_primary',
        'location_phone_secondary',
        'location_phone_sales',
        'location_contact_text',
        'location_city',
        'location_country',
        'location_map_latitude',
        'location_map_longitude',
        'faq_title',
        'faq_content',
        'faq_show_section',
        'legal_terms_content',
        'legal_privacy_content',
        'legal_returns_content',
        'nav_top_bg',
        'nav_top_text',
        'nav_top_hover',
        'nav_header_from',
        'nav_header_via',
        'nav_header_to',
        'footer_from',
        'footer_via',
        'footer_to',
        'footer_text',
        'footer_muted',
        'typography_font_family',
        'typography_font_url',
        'payphone_enabled',
        'payphone_token',
        'payphone_store_id',
        'payphone_environment',
        'payphone_domain',
        'payphone_api_url',
    ];

    protected $casts = [
        'payphone_enabled' => 'boolean',
        'payphone_token' => 'encrypted',
    ];
}
